touch library/algebra/matrix/ntm_matrix_algebra.java
touch library/algebra/scalar/ntm_scalar_algebra.java
touch library/algebra/tensor/ntm_tensor_algebra.java
touch library/algebra/vector/ntm_vector_algebra.java
touch library/arithmetic/matrix/ntm_matrix_arithmetic.java
touch library/arithmetic/scalar/ntm_scalar_arithmetic.java
touch library/arithmetic/tensor/ntm_tensor_arithmetic.java
touch library/arithmetic/vector/ntm_vector_arithmetic.java
touch library/math/matrix/ntm_matrix_math.java
touch library/math/scalar/ntm_scalar_math.java
touch library/math/vector/ntm_vector_math.java
touch library/nn/ann/components/ntm_masked_multi_head_attention.java
touch library/nn/ann/components/ntm_masked_scaled_dot_product_attention.java
touch library/nn/ann/components/ntm_multi_head_attention.java
touch library/nn/ann/components/ntm_scaled_dot_product_attention.java
touch library/nn/ann/controller/fnn/ntm_fnn.java
touch library/nn/ann/controller/lstm/ntm_lstm.java
touch library/nn/ann/functions/ntm_layer_norm.java
touch library/nn/ann/functions/ntm_positional_encoding.java
touch library/nn/ann/inputs/ntm_inputs_vector.java
touch library/nn/ann/inputs/ntm_keys_vector.java
touch library/nn/ann/inputs/ntm_queries_vector.java
touch library/nn/ann/inputs/ntm_values_vector.java
touch library/nn/ann/top/ntm_controller.java
touch library/nn/ann/top/ntm_decoder.java
touch library/nn/ann/top/ntm_encoder.java
touch library/nn/fnn/convolutional/ntm_controller.java
touch library/nn/fnn/standard/ntm_controller.java
touch library/nn/lstm/convolutional/ntm_activation_gate_vector.java
touch library/nn/lstm/convolutional/ntm_controller.java
touch library/nn/lstm/convolutional/ntm_forget_gate_vector.java
touch library/nn/lstm/convolutional/ntm_hidden_gate_vector.java
touch library/nn/lstm/convolutional/ntm_input_gate_vector.java
touch library/nn/lstm/convolutional/ntm_output_gate_vector.java
touch library/nn/lstm/convolutional/ntm_state_gate_vector.java
touch library/nn/lstm/standard/ntm_activation_gate_vector.java
touch library/nn/lstm/standard/ntm_controller.java
touch library/nn/lstm/standard/ntm_forget_gate_vector.java
touch library/nn/lstm/standard/ntm_hidden_gate_vector.java
touch library/nn/lstm/standard/ntm_input_gate_vector.java
touch library/nn/lstm/standard/ntm_output_gate_vector.java
touch library/nn/lstm/standard/ntm_state_gate_vector.java
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.java
touch library/trainer/differentiation/ntm_vector_controller_differentiation.java
touch library/trainer/fnn/ntm_fnn_b_trainer.java
touch library/trainer/fnn/ntm_fnn_d_trainer.java
touch library/trainer/fnn/ntm_fnn_k_trainer.java
touch library/trainer/fnn/ntm_fnn_trainer.java
touch library/trainer/fnn/ntm_fnn_u_trainer.java
touch library/trainer/fnn/ntm_fnn_v_trainer.java
touch library/trainer/fnn/ntm_fnn_w_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_b_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_d_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_k_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_u_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_v_trainer.java
touch library/trainer/lstm/activation/ntm_lstm_activation_w_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_b_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_d_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_k_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_u_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_v_trainer.java
touch library/trainer/lstm/forget/ntm_lstm_forget_w_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_b_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_d_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_k_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_u_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_v_trainer.java
touch library/trainer/lstm/input/ntm_lstm_input_w_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_b_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_d_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_k_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_u_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_v_trainer.java
touch library/trainer/lstm/output/ntm_lstm_output_w_trainer.java
